- docs/.vitepress/sidebar.ts
- docs/contributors.json
- docs/index.md
- docs/program/vitepress-local-search/index.md
add vitepress local search article
> feat: add vitepress local search

- docs/.vitepress/theme/components/DataPanel.vue
- docs/.vitepress/theme/index.ts
- docs/.vitepress/theme/plugins/busuanzi.ts
- docs/index.md
> feat(theme): add data panel uv pv plugin

- docs/.vitepress/sidebar.ts
- docs/interview/js/test/1.md
- docs/interview/js/test/2.md
- docs/interview/js/test/3.md
> feat(interview): add js test list

- docs/.vitepress/config.ts
- docs/.vitepress/theme/components/PageInfo.vue
busuanzi page pv add container
---
> fix(theme): busuanzi page pv add container

- docs/.vitepress/theme/components/PageInfo.vue
> fix(theme): text show

- docs/.vitepress/theme/components/DataPanel.vue
> style: mobile add px

- docs/.vitepress/theme/plugins/autoSidebarBeta.ts
> feat(plugin): optimize plugin code

- docs/contributors.json
- package.json
> chore: release v0.2.1

- docs/.vitepress/sidebar.ts
- docs/tool/github520.md
feat(tool): add github 520
---
> feat(tool): add github 520

- docs/.vitepress/sidebar.ts
- docs/patterns/observer-pattern/index.md
> feat(patterns): add observer pattern

- docs/.vitepress/sidebar.ts
- docs/patterns/module-pattern/index.md
> feat(pattern): add module pattern

- docs/.vitepress/sidebar.ts
- docs/patterns/mixin-pattern/index.md
> feat(pattern): add mixin pattern

- docs/.vitepress/theme/utils/date.ts
> fix(utils): add dayjs zh-cn

- docs/.vitepress/theme/index.ts
- docs/.vitepress/theme/styles/main.css
- package.json
- pnpm-lock.yaml
re #181
feat(theme): images to be zoomed in on click #181
---
> feat(theme): images to be zoomed in on click

- docs/.vitepress/algolia.ts
- docs/.vitepress/config.ts
- docs/.vitepress/meta.ts
- docs/index.md
> feat(theme): update site info

- docs/.vitepress/config.ts
> style: text update

- docs/.vitepress/config.ts
> fix: no clean urls

- README.md
- docs/.vitepress/config.ts
- docs/guide.md
- docs/index.md
> feat(theme): add alternate site

- docs/.vitepress/theme/plugins/autoSidebarBeta.ts
- docs/patterns/module-pattern/index.md
- docs/vite.config.ts
- package.json
- pnpm-lock.yaml
- scripts/release.ts
- scripts/utils.ts
> chore: upgrade package

- docs/index.md
> feat(theme): custom features links

- docs/.vitepress/config.ts
- docs/.vitepress/meta.ts
- docs/.vitepress/plugins/pwa.ts
- docs/.vitepress/theme/components/HomeContributors.vue
- docs/contributors.json
- docs/contributors.ts
- docs/index.md
- package.json
- pnpm-lock.yaml
- scripts/update.ts
- scripts/utils.ts
use @vite-pwa/vitepress and update docs home
---
> feat(theme): use @vite-pwa/vitepress and update docs home

- docs/.vitepress/sidebar.ts
- docs/patterns/hoc-pattern/index.md
feat(pattern): add hoc pattern
---
> feat(pattern): add hoc pattern

- docs/contributors.json
- package.json
auto generate contributors
---
> chore: release v0.2.2

- docs/weekly/202303.md
feat(weekly): update 03 and add 04
---
> feat(weekly): update 03 and add 04

- docs/.vitepress/sidebar.ts
- docs/nextjs/sitemap/index.md
feat(nextjs): add post about sitemap generator for next.js
---
> feat(nextjs): add post about sitemap generator for next.js

- docs/.vitepress/sidebar.ts
- docs/vuejs/vue3-management-system/index.md
- pnpm-lock.yaml
> feat: add vue3-management-system md

- pnpm-lock.yaml
> fix: use pnpm@8 install

- docs/.vitepress/plugins/genFeed.ts
- docs/.vitepress/theme/components/Contributors.vue
- docs/.vitepress/theme/components/CopyRight.vue
- docs/.vitepress/theme/components/NavCard.vue
- docs/.vitepress/theme/components/PageInfo.vue
- docs/.vitepress/theme/plugins/autoSidebarBeta.ts
- docs/.vitepress/theme/plugins/googleAnalytics.ts
- docs/.vitepress/theme/utils/date.ts
- docs/.vitepress/theme/utils/pageInfo.ts
- docs/contributors.ts
- docs/interview/react-summary/index.md
- docs/nextjs/sitemap/index.md
- docs/patterns/provider-pattern/index.md
- docs/patterns/proxy-pattern/demo1.vue
- docs/patterns/proxy-pattern/demo2.vue
- docs/patterns/proxy-pattern/demo3.vue
- docs/patterns/singleton-pattern/demo2.vue
- docs/tool/off-time/demo.vue
ci: use latest eslint-config to lint fix
---
> ci: use latest eslint-config to lint fix

- docs/.vitepress/plugins/genFeed.ts
- docs/.vitepress/theme/components/Contributors.vue
- docs/.vitepress/theme/components/CopyRight.vue
- docs/.vitepress/theme/components/NavCard.vue
- docs/.vitepress/theme/components/PageInfo.vue
- docs/.vitepress/theme/index.ts
- docs/.vitepress/theme/plugins/autoSidebarBeta.ts
- docs/.vitepress/theme/plugins/googleAnalytics.ts
- docs/.vitepress/theme/plugins/pwa.ts
- docs/.vitepress/theme/utils/date.ts
- docs/.vitepress/theme/utils/pageInfo.ts
- docs/contributors.ts
- docs/interview/react-summary/index.md
- docs/nextjs/sitemap/index.md
- docs/patterns/provider-pattern/index.md
- docs/patterns/proxy-pattern/demo1.vue
- docs/patterns/proxy-pattern/demo2.vue
- docs/patterns/proxy-pattern/demo3.vue
- docs/patterns/singleton-pattern/demo2.vue
- docs/tool/off-time/demo.vue
use virtual:pwa-register to dynamic import
---
> fix: use virtual:pwa-register to dynamic import

- docs/.vitepress/config.ts
- package.json
feat(theme): add umami analytics
re #229
---
> feat(theme): add umami analytics

- docs/.vitepress/plugins/genFeed.ts
feat(theme): add feed
re #172 
---
> feat(theme): add feed

- docs/.vitepress/plugins/genFeed.ts
fix: add guid and update desc
re #172 
---
> fix: add guid and update desc

- docs/.vitepress/plugins/genFeed.ts
optimize rss object of date
re #127 
---
> feat(rss): optimize rss object of date

- docs/.vitepress/plugins/genFeed.ts
fix(rss): fix title and author 
re #172 
---
> fix(rss): fix title and author

- docs/.vitepress/sidebar.ts
- docs/program/vitepress-plugin/index.md
feat(program): add chodocs vitepress config post
---
> feat(program): add chodocs vitepress config post

- docs/.vitepress/sidebar.ts
- docs/tool/git/index.md
> feat: add git learn md

- docs/.vitepress/theme/components/CustomLink.vue
- docs/.vitepress/theme/utils/md.ts
- docs/weekly/202303.md
- docs/weekly/202304.md
- docs/weekly/202305.md
- docs/weekly/guide.md
feat(theme): link enhance
re #261 
---
> feat(theme): link enhance

- docs/.vitepress/sidebar.ts
- docs/program/trpc/index.md
feat(program): publish about trpc post
---
> feat(program): publish about trpc post

- docs/.vitepress/config.ts
> fix: chinese display in algolia search box

- docs/interview/spring-internship/bytedance1/index.md
> docs: update interview about event loop

- docs/.vitepress/theme/styles/medium-zoom.css
---
- [ ✅ ] Other
- [ ✅ ] 已阅读「[参与贡献指南](https://chodocs.cn/contributing.html)」
- [ ✅ ] 代码提交没有冲突并且已经通过格式化校验规则
> docs: be consistent with the file name
